# Generated by Django 5.0.1 on 2024-01-17 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADDSECTION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_date', models.DateField(default=django.utils.timezone.now)),
                ('sec_duration1', models.TimeField()),
                ('sec_duration2', models.TimeField()),
                ('sec_department', models.CharField(max_length=200)),
                ('sec_op_no', models.IntegerField()),
                ('sec_break1', models.TimeField()),
                ('sec_break2', models.TimeField()),
                ('sec_doctor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='APPOINTMENTSAVED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField()),
                ('app_date', models.DateField()),
                ('app_Name', models.CharField(max_length=100)),
                ('app_age', models.IntegerField()),
                ('app_gender', models.CharField(max_length=100)),
                ('app_Appointed_doctor', models.CharField(max_length=100)),
                ('app_discription', models.TextField()),
                ('app_op_no', models.IntegerField()),
                ('app_department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feeback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField()),
                ('patient_gender', models.CharField(max_length=10)),
                ('patient_phone', models.IntegerField()),
                ('patient_address', models.TextField()),
                ('patient_discription', models.TextField(blank=True)),
                ('patient_reg_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
