# Generated by Django 5.0.1 on 2024-01-17 21:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentsaved',
            name='app_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
