# Generated by Django 5.0.1 on 2024-01-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard_app', '0002_alter_appointmentsaved_app_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsaved',
            name='app_doctor_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='appointmentsaved',
            name='app_mark',
            field=models.CharField(default=None, max_length=6, null=True),
        ),
    ]
