# Generated by Django 5.0.1 on 2024-01-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard_app', '0003_appointmentsaved_app_doctor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentsaved',
            name='app_mark',
            field=models.BooleanField(default=False),
        ),
    ]
