# Generated by Django 5.0.1 on 2024-01-19 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard_app', '0004_alter_appointmentsaved_app_mark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='', max_length=100)),
                ('category', models.CharField(default='', max_length=50)),
                ('desc1', models.CharField(default='', max_length=300)),
                ('desc2', models.CharField(default='', max_length=3000)),
                ('exp_date', models.DateField()),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='user/images')),
                ('discount', models.IntegerField(default=0)),
                ('features', models.CharField(default='', max_length=1000)),
                ('use', models.CharField(default='', max_length=1000)),
                ('Quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Table',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=500)),
                ('amount', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=111)),
                ('address', models.CharField(max_length=1110)),
                ('city', models.CharField(max_length=110)),
                ('state', models.CharField(max_length=110)),
                ('zip_code', models.CharField(max_length=110)),
                ('phone', models.CharField(default='', max_length=110)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderUpd',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=5000)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Data',
            fields=[
                ('quantity', models.PositiveIntegerField(default=0)),
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='DashBoard_app.productlist')),
            ],
        ),
    ]
