# Generated by Django 5.0.1 on 2024-01-19 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard_app', '0005_productlist_order_table_orderupd_cart_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_table',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderupd',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart_Data',
        ),
        migrations.DeleteModel(
            name='Order_Table',
        ),
        migrations.DeleteModel(
            name='OrderUpd',
        ),
    ]
