# Generated by Django 5.0.1 on 2024-01-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard_app', '0006_remove_order_table_user_remove_orderupd_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsaved',
            name='app_doctor_priscription',
            field=models.TextField(default=True),
        ),
    ]
