# Generated by Django 5.0.1 on 2024-01-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard_app', '0007_appointmentsaved_app_doctor_priscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlist',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='productlist',
            name='features',
        ),
        migrations.RemoveField(
            model_name='productlist',
            name='image',
        ),
        migrations.AddField(
            model_name='appointmentsaved',
            name='app_medicine',
            field=models.TextField(default=True),
        ),
    ]
