# Generated by Django 5.0.1 on 2024-01-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard_app', '0008_remove_productlist_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlist',
            old_name='product_name',
            new_name='generic_name',
        ),
    ]
