# Generated by Django 5.0.1 on 2024-01-21 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard_app', '0009_rename_product_name_productlist_generic_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APPOINTMENTSAVED',
        ),
    ]
