# Generated by Django 5.0.1 on 2024-01-21 13:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard_app', '0010_delete_appointmentsaved'),
    ]

    operations = [
        migrations.CreateModel(
            name='APPOINTMENTSAVED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField()),
                ('app_date', models.DateField(default=django.utils.timezone.now)),
                ('app_Name', models.CharField(max_length=100)),
                ('app_age', models.IntegerField()),
                ('app_gender', models.CharField(max_length=100)),
                ('app_Appointed_doctor', models.CharField(max_length=100)),
                ('app_discription', models.TextField()),
                ('app_op_no', models.IntegerField()),
                ('app_department', models.CharField(max_length=100)),
                ('app_doctor_id', models.IntegerField(null=True)),
                ('app_mark', models.BooleanField(default=False)),
                ('app_doctor_priscription', models.TextField(default=True)),
                ('app_medicine', models.TextField(default=True)),
                ('app_frequency', models.CharField(max_length=100)),
                ('app_startdate', models.DateField(default=django.utils.timezone.now)),
                ('app_refills_remaining', models.CharField(max_length=100)),
            ],
        ),
    ]
