# Generated by Django 5.0.1 on 2024-01-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard_app', '0011_appointmentsaved'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsaved',
            name='app_enddate',
            field=models.DateField(null=True),
        ),
    ]
