# Generated by Django 5.0.1 on 2024-01-21 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard_app', '0012_appointmentsaved_app_enddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlist',
            old_name='product_id',
            new_name='medicine_id',
        ),
    ]
