# Generated by Django 5.0.1 on 2024-01-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard_app', '0013_rename_product_id_productlist_medicine_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductList',
            new_name='MedicineList',
        ),
    ]
