# Generated by Django 5.0.1 on 2024-01-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard_app', '0014_rename_productlist_medicinelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100)),
                ('dept_op_nos', models.IntegerField()),
                ('dept_head_of_dept', models.CharField(max_length=100)),
                ('dept_discription', models.TextField(default=True)),
                ('dept_contact', models.IntegerField()),
                ('dept_doctor', models.CharField(max_length=100)),
            ],
        ),
    ]
