# Generated by Django 5.0.1 on 2024-01-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard_app', '0015_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_doctor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
