# Generated by Django 5.0.1 on 2024-01-22 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard_app', '0016_alter_department_dept_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='dept_doctor',
        ),
    ]
