# Generated by Django 5.0.1 on 2024-01-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard_app', '0017_remove_department_dept_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_discription',
            field=models.TextField(null=True),
        ),
    ]
