# Generated by Django 5.0.1 on 2024-01-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard_app', '0018_alter_department_dept_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentsaved',
            name='app_doctor_priscription',
            field=models.TextField(null=True),
        ),
    ]
