# Generated by Django 5.0.1 on 2024-01-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard_app', '0019_alter_appointmentsaved_app_doctor_priscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsaved',
            name='app_dosage',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
