# Generated by Django 5.0.1 on 2024-01-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard_app', '0020_appointmentsaved_app_dosage'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsaved',
            name='app_Route_0f_administration',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
