# Generated by Django 5.0.1 on 2024-01-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard_app', '0021_appointmentsaved_app_route_0f_administration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100)),
                ('staff_age', models.IntegerField()),
                ('staff_gender', models.CharField(max_length=20)),
                ('staff_phone_no', models.IntegerField()),
                ('staff_address', models.TextField()),
                ('staff_role', models.CharField(max_length=100)),
            ],
        ),
    ]
