# Generated by Django 5.0.1 on 2024-01-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard_app', '0022_staffs'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsaved',
            name='app_medicine_dosage',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='appointmentsaved',
            name='app_medicine_duration',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='appointmentsaved',
            name='app_medicine_priscribed',
            field=models.TextField(default=True),
        ),
    ]
