# Generated by Django 5.0.1 on 2024-01-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard_app', '0023_appointmentsaved_app_medicine_dosage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsaved',
            name='app_advice_given',
            field=models.TextField(default=True),
        ),
    ]
