# Generated by Django 5.0.1 on 2024-01-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard_app', '0024_appointmentsaved_app_advice_given'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentsaved',
            name='app_advice_given',
            field=models.TextField(blank=True, default=True, null=True),
        ),
    ]
