# Generated by Django 5.0.1 on 2024-01-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard_app', '0026_alter_addsection_id_alter_appointmentsaved_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addsection',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appointmentsaved',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicinelist',
            name='medicine_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patienttable',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
