# Generated by Django 5.0.1 on 2024-01-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard_app', '0027_alter_addsection_id_alter_appointmentsaved_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsaved',
            name='aap_fee',
            field=models.IntegerField(default='0'),
        ),
    ]
