# Generated by Django 5.0.1 on 2024-01-26 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard_app', '0028_appointmentsaved_aap_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentsaved',
            old_name='aap_fee',
            new_name='app_fee',
        ),
    ]
