# Generated by Django 5.0.1 on 2024-01-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard_app', '0029_rename_aap_fee_appointmentsaved_app_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_profit', models.IntegerField()),
                ('patient_profit', models.IntegerField()),
            ],
        ),
    ]
