# Generated by Django 5.0.1 on 2024-01-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard_app', '0030_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='patient_profit',
            field=models.IntegerField(default=0),
        ),
    ]
